- include_tasks: tasks/key-management.yml

- name: Setup default git configuraiton
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "Fernando Pelaez T" }
    - {name: "user.email", value: "fernando.pelaez@cwc.com" }

- name: Download NPM Package
  shell: curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -
  ignore_errors: True

- name: Install NPM Package
  yum: 
    name:
      - nodejs
    state: present

- name: Clone remote from git
  git:
    repo="{{ git.repo }}"
    dest="{{ timeoff.release_path }}"
    accept_hostkey=yes
    key_file={{ git.key_file }}
    version={{ git.branch }}

#- name: Install NPM Application
#  command: chdir=/home/timeoff-management npm install
#  ignore_errors: True

#- name: Install NPM Application
#  command: chdir=/home/timeoff-management npm fix audit
#  ignore_errors: True

#- name: Start NPM Application
#  shell: cd /home/timeoff-management; ( ( nohup npm start </dev/null >/dev/null 2>&1 ) & )
#  ignore_errors: True
